# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Root Dependencies
        run: yarn install

      - name: Install Client Dependencies
        working-directory: ./packages/client/
        run: yarn install

      - name: Install Next
        working-directory: ./packages/client/
        run: npm install -g next react react-dom # yarn add next react react-dom => failed

      - name: Build Project
        working-directory: ./packages/client/
        run: next build && next export

      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          inlineScript: az storage blob upload-batch -d $web -s .packages/client/out --account-name {{ secrets.AZURESTORAGEACCOUNTNAME }} --account-key {{ secrets.AZURESTORAGEACCOUNTKEY }}
          
